name: Create Issues from TODO.md
on:
  push:
    paths:
      - 'react-app/todo.md'
jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse TODO.md and create issues
        uses: alstr/todo-to-issue-action@v4
        with:
          LABEL: 'auto-todo'
      - name: Auto-assign issues
        uses: kentaro-m/auto-assign-action@v1.2.1
  
